repos:
  - repo: builtin
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: detect-private-key
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.269.1
    hooks:
      - id: renovate-config-validator
