[tools]
go = "1.27"
cargo-binstall = "1.21.1"
golangci-lint = "v2.13.1"
gotestsum = "1.13.0"
just = "1.58.0"
fzf = "0.74.3"
bat = "0.26.1"
"cargo:eza" = "0.23.5"
git-cliff = "2.13.1"
prek = "0.4.14"
uv = "0.12.5"
